# Generated by Django 4.1.3 on 2022-11-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_rating_date_alter_rating_numbered_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='numbered_rating',
            new_name='ratings',
        ),
    ]
