# Generated by Django 4.1.3 on 2022-11-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_numbered_rating_rating_ratings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-date']},
        ),
    ]
